name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build
        run: |
          bun install
          bunx vsce package
      - name: Get version from package.json
        id: get_version
        run: echo version=$(jq -r .version < package.json) >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vscode-wikipedia-agent-${{ steps.get_version.outputs.version }}.vsix